[package]
name = "libime-history-merge"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.117"
log = "0.4.14"
pager = "0.16.0"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
structopt = "0.3.26"

[dev-dependencies]
pretty_assertions = "1.1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Feb 03 2022, 11:51 [CST]
